#+TITLE: Criterion C -- Development 
*MAX WORD COUNT 1000*
*SCREENSHOTS*

* Short introduction
My program is an address book with the purpose of centrally keeping
track of my father's contacts. I wrote it and built the GUI in
Netbeans using Java.

* Summary list of all techniques
- List of all basic Java stuff I used
* Structure of the program
  - Why oop
  - class structure
* Data strucutres used
  - what
  - why
* algorithms
  - what
  - why
* user-interface
  - The UI for my program is a GUI made with Java Swing Components
    using Netbeans' drag-and-drop tool. I chose to use this tool
    instead of writing the Swing code myself due to its relative speed
    and ease of use.
  - *Screenshots*
  - While text-based user interfaces are usually faster, more
    powerful, and more elegant than most graphical interfaces, they
    usually have a relatively high learning curve. My client, though
    moderately tech-literate, prefers GUIs over CLIs due to their
    lower learning curve. Furthermore, his choice of OS (MacOS) is
    centered around GUIs, such that using a CLI program in an elegant
    fashion would require extensive customization when compared to
    other operating systems like GNU/Linux.  
* software tools used
  - For the programming stage I would have prefered to use a simple,
    lightweight, and comfortable text editor like Vim or GNU/Emacs,
    however the relative difficulty of manually writing Java Swing
    elements forced me to turn to the Netbeans IDE. Beyond it's GUI
    building tools, I only used the very basic text editing features
    of Netbeans, prefering to manage backups on GitHub with the
    command-line git client built into my OS. I also made extensive
    use of GNU/Emacs' Org-Mode to work on criterions A, B, and C.  
  - *Screenshots of working environment*
